# Generated by Django 6.1.1 on 2026-09-07 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug Report'), ('suggestion', 'Suggestion / Feature Request'), ('compliment', 'Compliment'), ('other', 'Other')], default='suggestion', max_length=15)),
                ('rating', models.PositiveSmallIntegerField(default=3)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField()),
                ('may_contact', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('Crime', 'Crime'), ('Sci-Fi', 'Sci-Fi'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Action', 'Action'), ('Anime', 'Anime'), ('Documentary', 'Documentary'), ('Romance', 'Romance')], default='Drama', max_length=20)),
                ('cast', models.CharField(blank=True, help_text='Comma-separated list of lead cast members', max_length=300)),
                ('creator', models.CharField(blank=True, max_length=120)),
                ('release_year', models.PositiveIntegerField(default=2024)),
                ('seasons', models.PositiveSmallIntegerField(default=1)),
                ('maturity_rating', models.CharField(choices=[('ALL', 'All Ages'), ('PG-13', 'PG-13'), ('TV-14', 'TV-14'), ('TV-MA', 'TV-MA'), ('R', 'R')], default='TV-14', max_length=10)),
                ('match_score', models.PositiveSmallIntegerField(default=90, help_text="Simulated 'percent match' shown to viewers (0-100)")),
                ('poster_url', models.URLField(max_length=500)),
                ('backdrop_url', models.URLField(blank=True, max_length=500)),
                ('netflix_url', models.URLField(blank=True, max_length=500)),
                ('trending', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('top10_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added_on'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('newsletter_opt_in', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
